### ISSUE TITLE
Not having a k8s microservices development workflow places a high burden on students

### ISSUE THREAD

**Issue by ericcgu** [udacity/nd064-c2-message-passing-projects-starter#7]
We have hook different services up in a VM k3s and write code locally on our PC or MAC.  Our Local code environment is not consistent with VM k3s environment.  This creates a tedious experience for students like myself who want to focus on the topics.

@sarah-udacity 

I highly recommend adding a section to show students how to properly write and deploy efficiently in a k3s/k8s microservices environment. The local PC and MAC does not have access to the other k3s services. Port forwarding is not the way. See below. 

Why this is important? 80% of the time on this project would be spent on ops, not code, most students i think would give up.

Thoughts? 

https://12factor.net/dev-prod-parity

https://skaffold.dev/docs/design/

https://www.youtube.com/watch?v=tTNrzEjROCo

**Comment by abhiojha8** [comment]
Thanks for the feedback. We will look into this when we refresh the course.
