### ISSUE TITLE
Replace Flask with FastAPI. Replace postgreSQL with MongoDB

### ISSUE THREAD

**Issue by ericcgu** [udacity/nd064-c2-message-passing-projects-starter#8]
The ML course is using FastAPI, which auto generates Open API and Swagger. It only has one model file, leveraging Pydantic. This python app could improve readability by simplifying the number of files and amount of code it uses for models and serialization. Every object has three files that need to be changed for any object updates. It's confusing.

Replace postgreSQL with MongoDB. MongoDB supports BSON/JSON so you dont need another file to support python object serialization to postgres sql objects + writing raw sql code just to persist data. It will support JSON to JSON in a clearly written way. Since the focus isn't on database, why not simplify and detract focus away from the subject being taught.

**Comment by d-alleyne** [comment]
@ericcgu what ML course are you referring to? I agree FastAPI is a better experience as a PHP developer. It is good to know that there are alternatives to PostGIS for performing Geometric queries.

**Comment by abhiojha8** [comment]
Thanks for the feedback. We will look into this when we refresh the course.
